# Shared roster: the 10-team field (as specs) + per-team plans. Used by the parallel
# worker, run_iteration, and evolve so they all agree on teams/plans.
require_relative 'teams'
require_relative 'my_team'
require_relative 'spec_extract'
require_relative 'editor'
require_relative 'claude_client'

module Roster
  PLANS = {
    "Sun"     => "SUN. Ninetales sets Drought. Wincons: Chlorophyll Venusaur (needs sun) + Regigigas/Gliscor (Poison Heal Facade, weather-INDEPENDENT = your safety valve). If enemy overwrites weather (Kyogre/Sand), STOP forcing sun sweeps; pivot to Regigigas + Blissey Sticky Web and grind. Spore-lock a threat early. Blaziken is 4x Rock - keep it off hazards.",
    "Rain"    => "RAIN. Politoed sets Drizzle. Wincons: Swift Swim sweepers (Ludicolo/Kabutops/Kingdra - DOUBLE speed in rain) + Togekiss Calm Mind (rain-independent backup). Kabutops Aqua Jet = priority revenge. If rain is overwritten, use Togekiss/priority, don't flounder. Don't loop Politoed's status - pivot with U-turn or attack.",
    "Sand"    => "SAND. Tyranitar sets Sand Stream. Physical DD sweepers, but ALL use Earthquake - a Ground-immune Flyer (Groudon/Gliscor) walls you; break it with Volcarona/Nidoking Ice Beam (4x) or Azumarill Waterfall. Azumarill has Aqua Jet priority - don't DD-loop in mirrors. Metagross holds Lum (eats one Spore).",
    "Squads"  => "LEGENDARY BALANCE. Kyogre sets Drizzle + Spore-locks. Core: Sylveon Pixilate ExtremeSpeed (priority nuke), Aegislash Spectral Thief/Whirlwind (phazes setup, steals boosts), Groudon/Gliscor (Poison Heal EQ wall). Ninetales also has Drought - do NOT activate it while your own Drizzle is up (they cancel).",
    "Box15A"  => "FAST LEGENDARY OFFENSE. Dragonite/Arceus (Multiscale DD + ExtremeSpeed) is the main wincon; Deoxys/Latios (Lum, fast) revenges; Reshiram/Clefable (Magic Guard LO) breaks walls freely. Dialga/Espeon Magic-Bounces Spore/hazards - lead it vs status. Kyogre/Toxapex Ice Beam 4x's Gliscor walls. Marowak/Arceus ExtremeSpeed is Ghost-IMMUNE - use Earthquake vs Ghosts.",
    "Box15B"  => "LEGENDARY BALANCE. Kyogre Drizzle + Spore-lock is the engine. Giratina Spectral Thief, Groudon Poison-Heal wall, Kyurem/Dialga (Scarf Moxie revenge, Icicle Crash 4x's Gliscor). Ninetales has Drought - don't overwrite your own Drizzle. Groudon is 4x Ice - keep it off Ice attacks. Dialga/Espeon Magic-Bounces status.",
    "Box15C"  => "SLOW TRICK ROOM. Reuniclus/Slowbro set Trick Room FIRST so your slow nukes (Marowak/Rhyperior Thick Club, Chandelure, Slaking) outspeed. Quagsire Water-Absorbs Kyogre's rain. No sleep answer - if slept, STAY IN and wait it out, never switch-loop. Weak to fast/weather; win by getting TR up and clicking your huge slow attackers.",
    "Momentum"=> "VOLTTURN MOMENTUM. Magnezone/Gardevoir + Weavile pivot with Volt Switch/U-turn to chip. Gengar/Rotom (Levitate) walls Ground teams - keep it healthy, Nasty Plot when safe. Weavile Scarf = revenge/speed control, save for cleanup; Icicle Crash 4x's Gliscor. Lucario/Scizor Bullet Punch answers Fairies (Sylveon).",
    "Overload"=> "HYPER-OFFENSE. Pick the SUPER move, punch holes, revenge with Scarf Electivire + priority (Bullet Punch/Ice Shard). Geninja (Protean) Taunts sleep/setup leads. Do NOT set up into Aegislash (Whirlwind/Spectral Thief) - just attack/revenge. No bulk - trade efficiently, don't get chip-worn.",
    "Bunker"  => "BULKY OFFENSE. Walls (Ferrothorn hazards, Blissey special wall) + wincons Suicune/Togekiss (Calm Mind, Ground-immune) & Dragonite/Scizor (Dragon Dance, Ice-neutral). Set hazards, wear them down, then sweep with a boosted wincon. Bisharp Sucker Punch/Knock Off priority. Preserve your wincon vs fast special + Spore.",
    "UbersOff" => "GEN5 UBERS HYPER-OFFENSE (vanilla control). Scarf Kyogre (Drizzle) = revenge + rain WaterSpout nuke; DD Rayquaza + Extreme Killer Arceus (Swords Dance -> ExtremeSpeed priority) sweep; Darkrai uses Dark Void to sleep a wall then Nasty Plot sweeps; Specs Dialga wallbreaks; Ferrothorn sets Rocks/Spikes. Lead hazards or Dark Void, clean with priority.",
    "UbersBal" => "GEN5 UBERS BALANCE (vanilla control). Groudon (Drought) + Kyogre (Drizzle) for weather + Stealth Rock; Dragon Tail phazes setup; Giratina walls (Will-O-Wisp / Rest-Sleep Talk); Choice Band Scizor Bullet Punch priority + Pursuit-traps; Calm Mind Latias & Nasty Plot Mewtwo are your late-game wincons. Set rocks, phaze, wear down, then sweep with a boosted CM/NP mon.",
    "Degen"    => "MAX-BROKEN FUSION. Kyogre/Arceus (Drizzle) Specs rain nuke; Marowak/Arceus @Thick Club = doubled Atk STAB ExtremeSpeed priority; Regigigas/Gliscor (Poison Heal bypasses Slow Start) SD sweeper; Mewtwo/Arceus fast Nasty Plot special; Giratina/Arceus Dragon Dance + ExtremeSpeed + Spectral Thief (steals boosts); Reshiram/Clefable (Magic Guard + Life Orb, no recoil) Calm Mind. Overwhelm with near-max-stat mons + priority + broken abilities.",
    "OU"       => "GEN5 OU BALANCE (vanilla control). Scarf Tyranitar (Sand Stream) revenge + Pursuit-trap; Ferrothorn hazards (SR/Spikes/Leech Seed); Gliscor (Poison Heal) EQ/Toxic/Roost stall; Life Orb Latios (Draco/Psyshock) breaker; Choice Band Scizor Bullet Punch/U-turn/Pursuit; Serene Grace Jirachi (Iron Head flinch + Wish). Set hazards, pivot, wear down, revenge with Scarf/priority.",
    "OUBalance"=> "OU BALANCE (fusion). Ferrothorn/Skarmory sets hazards (SR/Spikes) + Whirlwind phazes setup; Gliscor/Suicune (Poison Heal, EQ/Toxic/Roost) walls + pivots; Rotom/Gyarados (Levitate) VoltTurns + Will-O-Wisp burns; Starmie/Tentacruel Rapid-Spins hazards away (only hazard control). TWO win-cons: (1) Dragonite/Scizor (Multiscale Dragon Dance, Ice-neutral) DD-sweeps late; (2) Marowak/Mimikyu = your BREAKER - USE IT ACTIVELY. Its Disguise BLOCKS THE FIRST HIT, so switch it in freely on a resisted/weak attack and Swords Dance for FREE; Thick Club DOUBLES its Attack so Bonemerang (Ground) and Play Rough (Fairy) hit ENORMOUSLY (dual STAB); Shadow Sneak is PRIORITY to revenge-kill weakened or faster threats. Plan: bring Marowak/Mimikyu in behind Disguise, Swords Dance once, then sweep or Shadow-Sneak-snipe. Wear them down with hazards + walls, then close with a boosted Dragozor OR a Thick-Club Marowak.",
    "OURain"   => "OU RAIN (fusion) - this is a MOMENTUM/WEATHER team, not a spam-your-best-move team. Politoed/Whimsicott sets Drizzle on entry. KEY MECHANIC: weather abilities fire slowest-LAST, so leading Politoed WINS the weather war even against a faster opposing sand/sun setter (your Drizzle overwrites theirs) - do NOT fear leading it into their weather setter. THE WIN CONDITION: after rain is up, IMMEDIATELY U-TURN into a Swift Swim sweeper - Kingdra/Empoleon (special breaker, Draco/Hydro Pump) or Ludicolo/Sceptile (special, resists Water/Electric). In rain Swift Swimmers DOUBLE Speed (~470-670) and outrun the entire field - that is how you sweep. U-turn keeps momentum even when you move second. Azumarill/Marowak (Huge Power + Thick Club = QUADRUPLED Atk, Water/Ground ELECTRIC-IMMUNE) = PRIORITY NUKE that LOVES rain: AQUA JET is priority Water STAB, boosted by rain x1.5 on TOP of x4 Atk - it revenge-kills/cleans almost anything regardless of speed; Earthquake/Knock Off coverage, Swords Dance to end games. It is SLOW, lean on Aqua Jet priority (note: pure-Water foes RESIST it - use EQ/Knock Off there). Only STAY IN with Politoed to Scald/Ice Beam/Encore when there is a clear reason (revenge a low-HP foe, Encore-lock a setup sweeper, or no safe pivot) - do NOT just click Scald every turn. If your rain gets overwritten, bring Politoed back in to RE-SET it (it wins on entry). Swift Swimmers are frail Life Orb glass - pivot with U-turn, don't sit and get worn. Ferrothorn/Skarmory sets hazards + is the backbone. Dragonite/Scizor = rain-INDEPENDENT Dragon Dance wincon for when rain is contested.",
    "OUSun"    => "OU SUN (fusion). Ninetales/Whimsicott sets Drought + Spore-locks a threat. Chlorophyll sweepers DOUBLE speed in sun: Venusaur/Chandelure (special, instant Solar Beam + Draco) + Leafeon/Arcanine (physical Leaf Blade/Flare Blitz). Charizard/Hydreigon (Solar Power) breaks. Regigigas/Gliscor (Poison Heal Facade) = weather-INDEPENDENT wincon when sun is overwritten; Blissey/Shuckle walls + Sticky Web (speed control) + Rapid Spin (hazard control). Fire-mons are Rock-weak - keep Stealth Rock off your side via Blissey's spin.",
    "OUSand"   => "OU SAND (fusion). Tyranitar/Articuno (BULKY Rock/Flying anchor, Sand Stream) sets Stealth Rock + STONE EDGE (OHKOs Fire/Fairy sun setters, 4x) + U-TURN pivot + ROOST for longevity. Sand is PERMANENT in IF, so you don't need the setter alive to KEEP sand - but KEEP TYRANITAR/ARTICUNO ALIVE to RE-SET sand if a foe overwrites your weather (rain/sun/hail = weather war); its bulk + Roost let it TANK weather-boosted hits, re-set sand by switching back in, and keep laying hazards - use that, don't trade it cheaply. WEATHER-WAR MECHANIC: weather abilities fire slowest-LAST, so to reclaim weather SWITCH Tyranitar/Articuno back IN after the foe's weather is up (its Sand Stream fires on entry, overwrites). It is Rock/Flying = 2x weak to Water: vs rain-boosted Scald/Hydro Pump, Roost or pivot rather than sitting to die. Sand Rush Slaking/Sandslash is DEAD WEIGHT without sand (just base speed), so winning the weather war IS the game vs other weather teams - keep the setter and re-flip the weather rather than forcing sweeps under enemy weather. Metagross/Garchomp = Choice Scarf revenge killer (Steel/Ground RESISTS Ice, EQ/Iron Head/Outrage/Stone Edge). Ferrothorn/Skarmory hazards (SR/Spikes/Leech) + Whirlwind phaze. Slaking/Sandslash = SAND RUSH sweeper (DOUBLES Speed in sand, ~552): Swords Dance then sweep with THOUSAND ARROWS (Ground move that HITS Flying/Levitate + Steel/Flying - no immunities) + Ice Punch; also RAPID SPINS your hazards away. Regirock/Gliscor (POISON HEAL + Toxic Orb = heals 12.5%/turn once poisoned, BURN/status-immune after orb activates) = utility tank: Def 436 walls physical threats (Sucker Punch/CC/EQ users), and as a ROCK type its SpD is x1.5 IN SAND (~330 effective) so it takes special hits too; Rock/FLYING = IMMUNE to Earthquake/Ground and immune to Spikes. KNOCK OFF strips items, TOXIC clocks non-Steel/Poison walls, PROTECT banks free Poison Heal + toxic ticks - the classic loop: Toxic the target, Protect, Knock Off. Dragonite/Scizor (Multiscale) Dragon Dance wincon. Grind with sand+hazards, revenge with Scarf, Spin off hazards, sweep late with SD Sandslash or DD Dragozor.",
    "Ubers1"   => "UBERS BALANCE (fusion). Darkrai/Hydreigon (Levitate) Nasty Plot + Dark Pulse/Draco special breaker; Kyogre/Mew (Drizzle) Spore + Water Spout + Quiver Dance; Groudon/Gliscor (Poison Heal, Toxic Orb) Swords Dance EQ wall+sweeper, immune Ground+Electric; Kyurem/Metagross (Choice Scarf, Clear Body) revenge - Iron Head is your Fairy/Xerneas answer, Icicle Crash 4x's Gliscor/Dragons; Slaking/Dragonite (Multiscale, NO Truant) Extreme Speed priority wincon; Dialga/Espeon (Magic Bounce) bounces hazards/status + Stealth Rock + Calm Mind. Wall, phaze/scarf-revenge, then sweep with the Multiscale priority mon.",
    "Ubers2"   => "UBERS RAIN OFFENSE (fusion). Kyogre/Celebi (Drizzle) Specs Water Spout nuke; Kingdra/Zekrom (Swift Swim) Dragon Dance + Bolt Strike/Waterfall (doubled speed in rain); Palkia/Flygon (Levitate, Ground-immune) Calm Mind special breaker. Groudon/Gliscor (Poison Heal SD) + Aegislash/Lugia (Multiscale, Spectral Thief STEALS boosts + Whirlwind phaze) + Registeel/Ferrothorn (Steel/Grass, resists Electric, hazards + Power Whip) are the spine so you aren't pure glass. Overwhelm in rain, fall back on the spine, phaze setup.",
    # ---- GAUNTLET: hardest E4 + Champions (real AI teams, rebuilt L100) ----
    "Lorelei"  => "ICE / HAIL (E4). Every mon holds Never-Melt-Ice and can set Hail. Weavile/Lapras Perish-Song traps; Jynx/Tangrowth Sleep Powder + Ice Punch; Mamoswine/Slowbro Slack Off recovery. Ice STAB everywhere (4x on Dragon/Ground/Flying/Grass). Set Hail, chip, click Ice. Keep your Ice-weak mons back; wall the Ice with Water/Steel/Fire.",
    "Bruno"    => "FIGHTING (E4). Black Belt boosts Fighting. Scizor/Heracross Swords Dance then Close Combat/X-Scissor sweeps; Marowak/Hitmonchan Dynamic Punch + Bonemerang; Machamp/Electivire mixed punches; Magnezone/Onix Lock-On + Zap Cannon. Fighting is walled by Ghost/Flying/Psychic/Fairy - lead those. Revenge the SD sweeper before it snowballs.",
    "Agatha"   => "GHOST TRAP/STALL (E4). Spell Tag Ghosts. Gengar/Houndoom + Wobbuffet/Gengar spam DESTINY BOND (do NOT KO them with your wincon - chip/status instead), Wobbuffet Counter/Mirror Coat punishes attacks, Snorlax/Gengar Curse+Rest stalls. Ghost STAB. Wear them down with hazards/status; never trade your sweeper into Destiny Bond.",
    "Lance"    => "DRAGON (E4). Dragon Fang Dragons. Togekiss/Dragonite Moonblast/Outrage; Tyranitar/Aerodactyl Brave Bird/Head Smash + Agility; Typhlosion/Dragonair Dragon Dance + Fire Blast; Porygon2/Kingdra DD + Recover. Dragon STAB is walled by Fairy/Steel - lead those and revenge with Ice/Fairy. Watch the Agility/DD sweepers.",
    "BlueExpert" => "CHAMPION OFFENSE. Venusaur/Mamoswine (Thick Fat) Stealth Rock lead; Chandelure/Volcarona (SHADOW TAG - it TRAPS your switch! + Quiver Dance, Focus Sash) is the main sweeper; Blastoise/Scizor (Technician Bullet Punch/Aqua Jet PRIORITY + Swords Dance); Porygon-Z/Noivern (Adaptability Boomburst nuke); Sylveon/Dragonite (Pixilate Extreme Speed priority); Mew. Beware Shadow Tag trapping and layered priority - keep resists healthy, revenge the Quiver Dance sweeper fast.",
    "BlueRemix"  => "CHAMPION HAZARD OFFENSE. Shuckle/Klefki (Prankster STICKY WEB + hazards, fast lead - drops your Speed) sets up; Magnezone/Cofagrigus traps Steels; Metagross/Dhelmise Steelworker band; Garchomp/Weavile fast physical + Ice; Sylveon/Noivern Pixilate priority; Slaking/Dragonite (Multiscale, no Truant) Extreme Speed. Clear Sticky Web (spin/defog) or play around the -Speed; revenge the priority sweepers, don't get chip-trapped.",
  }

  module_function

  def plan(n); PLANS[n] || "Play type advantages, set up when safe, revenge with priority/scarf."; end

  # Field as {name => spec}. From reports/<tag>/field_specs.json if present, else the
  # base 10 (extracted from the save + my specs).
  def field(tag_dir = nil)
    f = tag_dir && File.join(tag_dir, 'field_specs.json')
    if f && File.exist?(f)
      ClaudeClient::PARSE.call(File.read(f)).transform_values { |t| t.map { |m| Editor.normalize(m) } }
    else
      SpecExtract.all
    end
  end
end
